#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcHealth
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HealthDB")]
	public partial class Linq2SQLDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserthealth(health instance);
    partial void Updatehealth(health instance);
    partial void Deletehealth(health instance);
    #endregion
		
		public Linq2SQLDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HealthDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Linq2SQLDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Linq2SQLDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Linq2SQLDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Linq2SQLDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<health> healths
		{
			get
			{
				return this.GetTable<health>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.health")]
	public partial class health : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DRG_Definition;
		
		private System.Nullable<double> _Provider_Id;
		
		private string _Provider_Name;
		
		private string _Provider_Street_Address;
		
		private string _Provider_City;
		
		private string _Provider_State;
		
		private System.Nullable<double> _Provider_Zip_Code;
		
		private string _Hospital_Referral_Region_Description;
		
		private System.Nullable<double> @__Total_Discharges_;
		
		private System.Nullable<decimal> @__Average_Covered_Charges_;
		
		private System.Nullable<decimal> @__Average_Total_Payments_;
		
		private int _ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDRG_DefinitionChanging(string value);
    partial void OnDRG_DefinitionChanged();
    partial void OnProvider_IdChanging(System.Nullable<double> value);
    partial void OnProvider_IdChanged();
    partial void OnProvider_NameChanging(string value);
    partial void OnProvider_NameChanged();
    partial void OnProvider_Street_AddressChanging(string value);
    partial void OnProvider_Street_AddressChanged();
    partial void OnProvider_CityChanging(string value);
    partial void OnProvider_CityChanged();
    partial void OnProvider_StateChanging(string value);
    partial void OnProvider_StateChanged();
    partial void OnProvider_Zip_CodeChanging(System.Nullable<double> value);
    partial void OnProvider_Zip_CodeChanged();
    partial void OnHospital_Referral_Region_DescriptionChanging(string value);
    partial void OnHospital_Referral_Region_DescriptionChanged();
    partial void On_Total_Discharges_Changing(System.Nullable<double> value);
    partial void On_Total_Discharges_Changed();
    partial void On_Average_Covered_Charges_Changing(System.Nullable<decimal> value);
    partial void On_Average_Covered_Charges_Changed();
    partial void On_Average_Total_Payments_Changing(System.Nullable<decimal> value);
    partial void On_Average_Total_Payments_Changed();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    #endregion
		
		public health()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DRG_Definition", DbType="NVarChar(255)")]
		public string DRG_Definition
		{
			get
			{
				return this._DRG_Definition;
			}
			set
			{
				if ((this._DRG_Definition != value))
				{
					this.OnDRG_DefinitionChanging(value);
					this.SendPropertyChanging();
					this._DRG_Definition = value;
					this.SendPropertyChanged("DRG_Definition");
					this.OnDRG_DefinitionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Provider_Id", DbType="Float")]
		public System.Nullable<double> Provider_Id
		{
			get
			{
				return this._Provider_Id;
			}
			set
			{
				if ((this._Provider_Id != value))
				{
					this.OnProvider_IdChanging(value);
					this.SendPropertyChanging();
					this._Provider_Id = value;
					this.SendPropertyChanged("Provider_Id");
					this.OnProvider_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Provider_Name", DbType="NVarChar(255)")]
		public string Provider_Name
		{
			get
			{
				return this._Provider_Name;
			}
			set
			{
				if ((this._Provider_Name != value))
				{
					this.OnProvider_NameChanging(value);
					this.SendPropertyChanging();
					this._Provider_Name = value;
					this.SendPropertyChanged("Provider_Name");
					this.OnProvider_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Provider_Street_Address", DbType="NVarChar(255)")]
		public string Provider_Street_Address
		{
			get
			{
				return this._Provider_Street_Address;
			}
			set
			{
				if ((this._Provider_Street_Address != value))
				{
					this.OnProvider_Street_AddressChanging(value);
					this.SendPropertyChanging();
					this._Provider_Street_Address = value;
					this.SendPropertyChanged("Provider_Street_Address");
					this.OnProvider_Street_AddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Provider_City", DbType="NVarChar(255)")]
		public string Provider_City
		{
			get
			{
				return this._Provider_City;
			}
			set
			{
				if ((this._Provider_City != value))
				{
					this.OnProvider_CityChanging(value);
					this.SendPropertyChanging();
					this._Provider_City = value;
					this.SendPropertyChanged("Provider_City");
					this.OnProvider_CityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Provider_State", DbType="NVarChar(255)")]
		public string Provider_State
		{
			get
			{
				return this._Provider_State;
			}
			set
			{
				if ((this._Provider_State != value))
				{
					this.OnProvider_StateChanging(value);
					this.SendPropertyChanging();
					this._Provider_State = value;
					this.SendPropertyChanged("Provider_State");
					this.OnProvider_StateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Provider_Zip_Code", DbType="Float")]
		public System.Nullable<double> Provider_Zip_Code
		{
			get
			{
				return this._Provider_Zip_Code;
			}
			set
			{
				if ((this._Provider_Zip_Code != value))
				{
					this.OnProvider_Zip_CodeChanging(value);
					this.SendPropertyChanging();
					this._Provider_Zip_Code = value;
					this.SendPropertyChanged("Provider_Zip_Code");
					this.OnProvider_Zip_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hospital_Referral_Region_Description", DbType="NVarChar(255)")]
		public string Hospital_Referral_Region_Description
		{
			get
			{
				return this._Hospital_Referral_Region_Description;
			}
			set
			{
				if ((this._Hospital_Referral_Region_Description != value))
				{
					this.OnHospital_Referral_Region_DescriptionChanging(value);
					this.SendPropertyChanging();
					this._Hospital_Referral_Region_Description = value;
					this.SendPropertyChanged("Hospital_Referral_Region_Description");
					this.OnHospital_Referral_Region_DescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_Total_Discharges_]", Storage="__Total_Discharges_", DbType="Float")]
		public System.Nullable<double> _Total_Discharges_
		{
			get
			{
				return this.@__Total_Discharges_;
			}
			set
			{
				if ((this.@__Total_Discharges_ != value))
				{
					this.On_Total_Discharges_Changing(value);
					this.SendPropertyChanging();
					this.@__Total_Discharges_ = value;
					this.SendPropertyChanged("_Total_Discharges_");
					this.On_Total_Discharges_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_Average_Covered_Charges_]", Storage="__Average_Covered_Charges_", DbType="Money")]
		public System.Nullable<decimal> _Average_Covered_Charges_
		{
			get
			{
				return this.@__Average_Covered_Charges_;
			}
			set
			{
				if ((this.@__Average_Covered_Charges_ != value))
				{
					this.On_Average_Covered_Charges_Changing(value);
					this.SendPropertyChanging();
					this.@__Average_Covered_Charges_ = value;
					this.SendPropertyChanged("_Average_Covered_Charges_");
					this.On_Average_Covered_Charges_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_Average_Total_Payments_]", Storage="__Average_Total_Payments_", DbType="Money")]
		public System.Nullable<decimal> _Average_Total_Payments_
		{
			get
			{
				return this.@__Average_Total_Payments_;
			}
			set
			{
				if ((this.@__Average_Total_Payments_ != value))
				{
					this.On_Average_Total_Payments_Changing(value);
					this.SendPropertyChanging();
					this.@__Average_Total_Payments_ = value;
					this.SendPropertyChanged("_Average_Total_Payments_");
					this.On_Average_Total_Payments_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
